apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-wrtn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-wrtn@sha256:fc3bd44d88bc27bb50fe584b49c12477ced3448147a07af9f173d02619473890
        name: my-python
        resources: {}
status: {}
